import type { Post } from "./types";

export const mockPosts: Post[] = [
  // --- OFFRES ---
  {
    id: "mock-1",
    type: "offer",
    category: "hebergement",
    title: "Maison avec 2 chambres disponibles",
    description:
      "Famille à La Teste-de-Buch, on peut accueillir 4-5 personnes. Animaux de compagnie bienvenus. Draps et repas fournis.",
    capacity: 5,
    lat: 44.6474,
    lng: -1.1556,
    locationName: "La Teste-de-Buch",
    contact: "0612345678",
    secretCode: "1234",
    status: "active",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "mock-2",
    type: "offer",
    category: "animaux",
    title: "Van + box pour chevaux",
    description:
      "J'ai un van 2 chevaux et un pré sécurisé à Biganos. Peux récupérer et héberger chevaux/ânes. Disponible 7j/7.",
    capacity: 2,
    lat: 44.6372,
    lng: -0.9497,
    locationName: "Biganos",
    contact: "0687654321",
    secretCode: "4567",
    status: "active",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "mock-3",
    type: "offer",
    category: "materiel",
    title: "Point d'eau et ravitaillement",
    description:
      "Commerce à Gujan-Mestras, distribution gratuite d'eau, nourriture et masques FFP2. Ouvert 8h-20h.",
    capacity: 0,
    lat: 44.6286,
    lng: -1.0364,
    locationName: "Gujan-Mestras",
    contact: "0556000000",
    secretCode: "7890",
    status: "active",
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "mock-4",
    type: "offer",
    category: "transport",
    title: "Covoiturage vers centres d'accueil",
    description:
      "Berline 5 places, peux transporter des familles de Arcachon vers les centres d'accueil de Bordeaux.",
    capacity: 4,
    lat: 44.6583,
    lng: -1.1732,
    locationName: "Arcachon",
    contact: "0611223344",
    secretCode: "2468",
    status: "active",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "mock-5",
    type: "offer",
    category: "hebergement",
    title: "Gîte rural — 8 places",
    description:
      "Gîte à Belin-Béliet, au sud des zones touchées. Calme, sécurisé. Idéal familles avec enfants.",
    capacity: 8,
    lat: 44.5186,
    lng: -0.7836,
    locationName: "Belin-Béliet",
    contact: "0699887766",
    secretCode: "1357",
    status: "active",
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "mock-6",
    type: "offer",
    category: "animaux",
    title: "Accueil chiens/chats urgents",
    description:
      "Refuge associatif à Mios, capacité 15 animaux. Nourriture fournie. Venir avec carnet de santé si possible.",
    capacity: 15,
    lat: 44.6181,
    lng: -0.8764,
    locationName: "Mios",
    contact: "0644556677",
    secretCode: "9876",
    status: "active",
    createdAt: new Date(Date.now() - 5400000).toISOString(),
  },

  // --- DEMANDES ---
  {
    id: "mock-7",
    type: "request",
    category: "hebergement",
    title: "Famille de 4 cherche hébergement urgent",
    description:
      "Évacués de Landiras, on a 2 enfants en bas âge. Besoin d'un toit pour cette nuit. On est à Hostens actuellement.",
    capacity: 4,
    lat: 44.5033,
    lng: -0.6553,
    locationName: "Hostens",
    contact: "0633445566",
    secretCode: "1111",
    status: "active",
    createdAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "mock-8",
    type: "request",
    category: "animaux",
    title: "Transport urgent pour 3 chevaux",
    description:
      "3 chevaux à Saumos, zone d'évacuation. Besoin d'un van ou camion rapidement. Pré non sécurisé.",
    capacity: 3,
    lat: 44.9936,
    lng: -1.1708,
    locationName: "Saumos",
    contact: "0677889900",
    secretCode: "2222",
    status: "active",
    createdAt: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: "mock-9",
    type: "request",
    category: "transport",
    title: "Personne âgée isolée — besoin transport",
    description:
      "Ma mère de 82 ans à Cazalis, ne peut pas conduire. Besoin d'un transport vers un centre d'accueil. Mobilité réduite.",
    capacity: 1,
    lat: 44.4667,
    lng: -0.5833,
    locationName: "Cazalis",
    contact: "0655443322",
    secretCode: "3333",
    status: "active",
    createdAt: new Date(Date.now() - 2700000).toISOString(),
  },
  {
    id: "mock-10",
    type: "request",
    category: "materiel",
    title: "Besoin masques FFP2 et eau potable",
    description:
      "Campement improvisé à Saint-Symphorien pour 12 personnes. Urgent : eau, masques, nourriture. Batteries mortes.",
    capacity: 12,
    lat: 44.5333,
    lng: -0.7167,
    locationName: "Saint-Symphorien",
    contact: "0612340000",
    secretCode: "4444",
    status: "active",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },

  // --- POINTS OFFICIELS ---
  {
    id: "mock-11",
    type: "official",
    category: "hebergement",
    title: "Centre d'accueil — Gymnase de La Teste",
    description:
      "Gymnase municipal ouvert 24h/24. Capacité 200 personnes. Eau, repas, sanitaires sur place. Numéro vert : 0 800 00 33 33.",
    capacity: 200,
    lat: 44.641,
    lng: -1.15,
    locationName: "La Teste-de-Buch",
    contact: "0800003333",
    secretCode: "0000",
    status: "active",
    createdAt: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: "mock-12",
    type: "official",
    category: "autre",
    title: "Poste de commandement — Pompiers 33",
    description:
      "PC opérationnel de la SDIS 33. Coordination des secours. Ne pas se présenter — appeler le 18 ou 112.",
    capacity: 0,
    lat: 44.8378,
    lng: -0.5792,
    locationName: "Bordeaux",
    contact: "18",
    secretCode: "0000",
    status: "active",
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: "mock-13",
    type: "official",
    category: "hebergement",
    title: "Centre d'accueil — Salle des fêtes Belin-Béliet",
    description:
      "Salle des fêtes équipée. Capacité 80 personnes. Vétérinaires sur place pour les animaux d'évolution.",
    capacity: 80,
    lat: 44.519,
    lng: -0.784,
    locationName: "Belin-Béliet",
    contact: "0556001122",
    secretCode: "0000",
    status: "active",
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
];
